language: python
install:
    #- sh build-without-pip.sh
    - git fetch --depth=500 
    - pip install --editable .
    - python setup.py install --root=/tmp/packages | grep -v '^copying'
script:
    - leo-console --version
    - /tmp/packages/home/travis/virtualenv/python2.7.14/bin/leo-console --version
    - pytest travis_tests/*

