language: python
install:
    #- sh build-without-pip.sh
    - git fetch --depth=500
    - git checkout tag/5.8-b1
    #- pip install --editable .
script:
    #- leo-console --version
    - python setup.py bdist_wheel
    - pip install dist/*.whl
    - leo-console --version

    - pytest travis_tests/*
