language: python
install:
    #- git fetch --tags --depth=500
    #- git checkout 5.8-b2
script:
    #- pip install --editable .
    #- leo-console --version
    # reverse grep to hide excessive 'adding' and 'copying'
    - python setup.py bdist_wheel | grep -v -e '^adding' -e '^copying'
    - pip install dist/*.whl
    - leo-console --version

    # There are no travis tests after checking out release tag
    #- pytest travis_tests/*
deploy:
  provider: pypi
  user: maphew
  password:
    - secure: ii42oxaVaVUxdQXLpkFbcHZwKkjvhuBrlu99N+39TJ7UjHt4R6YJkMH4ZW6JPdhfEdALwUbGdGKIZR5LenFkROyR6Ak+I9WjHtr0CQNgzf+rOMw7S1M/NQUjQPflKXh/f9Cc+HSnBk6h6GIG1Ot9K2KqQ37/HOOb7uYwsGwdImfyVkHQ2P6TVDNGcqyfqqtErWvXFKGESVRd/o9rA7rLA10MOADdl8/kDqYDTnOLiuDq5ggP168mqk8NNUzHk40gM93sWuU7Dui+idajCRWH0YjhJuDV0HWDZt93svKtfZ4Sb+LBtnyxr1bpULzWNhuqTguHZwCbU0NOZuJuoTbm7israUWIIwKEHE6f49oORnFjc8c4mHXHEewbfvlBsDSlY4eClkx2pyubyRPQLjoUNF4jqTtI/f5PSiCgFoBsRWiZC+Rhmfay504Oky6HWjAbDuy+08FcbOmGZzIHpTS97Fo4AXrZwsG77RMdHwA5DillLAcrKWNqZelFkZe6ZeBHpZCYJQpXYKbSFehg4BQApDf5soHapfnIAgEYRsIpLsSEmBe+Zr9fFINDxZxYyu+LhdNAS7t19J4yS9TorN4A79Ts0rR6je7CjTBFfN3Zkq+252iNwydUFUHYzlzB+/bS/2DY0pd0rZ6JSqf7ElcPpeRj4VuLlEs6EXH12sLQLws=
    secure: qkVZbj0W7OFIJ6bfcqD6Tm5Lp6qQl1QFHlFyDNZuCXPDNWkrY5e0RDZJsotlYaj811a9kqR+oz+QGbhRWk+ckLc+WLBrluY9ppG0C+KB0lbD53DPq1EfcE/Ug6GPptOcHtlFCY796QHwM3LXpYPSBH3WVn2qEqR1b1o1hkmBoZtIdZDeM4Wdxz3tf5tJlxNZihuidCIHCN5dEVuXZTI0697skUux90cGqpMBKX/RsV+6kuGy1lG41NPYPIhS7qhOwtZJrXA6NWPh6xO1pGsxNFy2aeFMeFS8odMZNRj9d9IQdG5kzvw+8dMs40XxWThwd600famWsNrODoDLOCYiOZxE3eMYI9u4l+A743ftqwqwCb5kBbAiwzGqM3rb6fYZySZr/2PQiMAEwibVYwqEq85M5cL7QchaC1WQw6lipC37CsPZQR3hQeBvGAQ58F0H1KK/UGldDZnYzXDYE5D+0cGbUKdVFSPTkXVLDSmIV0qmoxTFclW5IH2Knr565sAoQTIiSyWCvpN2U+nulKeqeYy/rXn54Q/T6nXZ61rqgONJ4XRxPBO2yekWgSFA+HFcbKPy9qczawsbuTUB5niL82+92vsua2Tx9YmUDS4G2PTwd2wvZtjfG8Y59aP+K/sNFUGFnb0MurzIDwZuKpSjEmojTuKLXw4GAW+mx0aZsro=
  on:
    tags: true
    branch: master

