language: python
install:
    - git fetch --depth=500
        # increase clone depth to ensure recent tags are present

    # install Leo dependencies
    - pip install docutils nbformat pylint pyflakes pypandoc sphinx
    - sudo apt install tree python-qt4

    # Install Leo in "distribution maintainer" mode
    - python setup.py install --root=/tmp/packages | grep -v '^copying'
        # hide too verbose 'Copying ...' messages

script:
    # ensure python knows where to find distrib-Leo
    - export PYTHONPATH=$PYTHONPATH:/tmp/packages/usr/lib/python2.7.14/site-packages

    # Does distrib-Leo run?
    - /tmp/packages/home/travis/virtualenv/python2.7.14/bin/leo-console --version

    #- tree -d /tmp/packages
    - pytest travis_tests/*

